<?php
    /**
     * AlphaKit - CountryList
     */
    
class CountryList
{
    public $countryList = array(
        "ad" => array("en" => "Andorra", "de" => "Andorra"),
        "ae" => array("en" => "United Arab Emirates", "de" => "Vereinigte Arabische Emirate"),
        "af" => array("en" => "Afghanistan", "de" => "Afghanistan"),
        "ag" => array("en" => "Antigua and Barbuda", "de" => "Antigua und Barbuda"),
        "ai" => array("en" => "Anguilla", "de" => "Anguilla"),
        "al" => array("en" => "Albania", "de" => "Albanien"),
        "am" => array("en" => "Armenia", "de" => "Armenien"),
        "an" => array("en" => "Netherlands Antilles", "de" => "Niederländische Antillen"),
        "ao" => array("en" => "Angola", "de" => "Angola"),
        "aq" => array("en" => "Antarctica", "de" => "Antarktis"),
        "ar" => array("en" => "Argentina", "de" => "Argentinien"),
        "as" => array("en" => "American Samoa", "de" => "Samoa"),
        "at" => array("en" => "Austria", "de" => "Österreich"),
        "au" => array("en" => "Australia", "de" => "Australien"),
        "aw" => array("en" => "Aruba", "de" => "Aruba"),
        "az" => array("en" => "Azerbaidjan", "de" => "Aserbaidschan"),
        "ba" => array("en" => "Bosnia-Herzegovina", "de" => "Bosnien-Herzegowina"),
        "bb" => array("en" => "Barbados", "de" => "Barbados"),
        "bd" => array("en" => "Bangladesh", "de" => "Bangladesh"),
        "be" => array("en" => "Belgium", "de" => "Belgien"),
        "bf" => array("en" => "Burkina Faso", "de" => "Burkina Faso"),
        "bg" => array("en" => "Bulgaria", "de" => "Bulgarien"),
        "bh" => array("en" => "Bahrain", "de" => "Bahrain"),
        "bi" => array("en" => "Burundi", "de" => "Burundi"),
        "bj" => array("en" => "Benin", "de" => "Benin"),
        "bm" => array("en" => "Bermuda", "de" => "Bermudas"),
        "bn" => array("en" => "Brunei Darussalam", "de" => "Brunei"),
        "bo" => array("en" => "Bolivia", "de" => "Bolivien"),
        "br" => array("en" => "Brazil", "de" => "Brasilien"),
        "bs" => array("en" => "Bahamas", "de" => "Bahamas"),
        "bt" => array("en" => "Bhutan", "de" => "Bhutan"),
        "bv" => array("en" => "Bouvet Island", "de" => "Bouvet Inseln"),
        "bw" => array("en" => "Botswana", "de" => "Botswana"),
        "by" => array("en" => "Belarus", "de" => "Weissrussland"),
        "bz" => array("en" => "Belize", "de" => "Belize"),
        "ca" => array("en" => "Canada", "de" => "Kanada"),
        "cc" => array("en" => "Cocos (Keeling) Islands", "de" => "Kokosinseln"),
        "cd" => array("en" => "Kongo", "de" => "Demokratische Republik Kongo"),
        "cf" => array("en" => "Central African Republic", "de" => "Zentralafrikanische Republik"),
        "cg" => array("en" => "Congo", "de" => "Kongo"),
        "ch" => array("en" => "Switzerland", "de" => "Schweiz"),
        "ci" => array("en" => "Ivory Coast (Cote D'Ivoire)", "de" => "Elfenbeinküste"),
        "ck" => array("en" => "Cook Islands", "de" => "Cook Inseln"),
        "cl" => array("en" => "Chile", "de" => "Chile"),
        "cm" => array("en" => "Cameroon", "de" => "Kamerun"),
        "cn" => array("en" => "China", "de" => "China"),
        "co" => array("en" => "Colombia", "de" => "Kolumbien"),
        "cr" => array("en" => "Costa Rica", "de" => "Costa Rica"),
        "cu" => array("en" => "Cuba", "de" => "Kuba"),
        "cv" => array("en" => "Cape Verde", "de" => "Kap Verde"),
        "cx" => array("en" => "Christmas Island", "de" => "Christmas Island"),
        "cy" => array("en" => "Cyprus", "de" => "Zypern"),
        "cz" => array("en" => "Czech Republic", "de" => "Tschechische Republik"),
        "de" => array("en" => "Germany", "de" => "Deutschland"),
        "dj" => array("en" => "Djibouti", "de" => "Djibuti"),
        "dk" => array("en" => "Denmark", "de" => "Dänemark"),
        "dm" => array("en" => "Dominica", "de" => "Dominika"),
        "do" => array("en" => "Dominican Republic", "de" => "Dominikanische Republik"),
        "dz" => array("en" => "Algeria", "de" => "Algerien"),
        "ec" => array("en" => "Ecuador", "de" => "Ecuador"),
        "ee" => array("en" => "Estonia", "de" => "Estland"),
        "eg" => array("en" => "Egypt", "de" => "Ägypten"),
        "eh" => array("en" => "Western Sahara", "de" => "Westsahara"),
        "er" => array("en" => "Eritrea", "de" => "Eritrea"),
        "es" => array("en" => "Spain", "de" => "Spanien"),
        "et" => array("en" => "Ethiopia", "de" => "Äthiopien"),
        "fi" => array("en" => "Finland", "de" => "Finnland"),
        "fj" => array("en" => "Fiji", "de" => "Fidschi"),
        "fk" => array("en" => "Falkland Islands", "de" => "Falkland Inseln"),
        "fm" => array("en" => "Micronesia", "de" => "Mikronesien"),
        "fo" => array("en" => "Faroe Islands", "de" => "Färöer Inseln"),
        "fr" => array("en" => "France", "de" => "Frankreich"),
        "ga" => array("en" => "Gabon", "de" => "Gabun"),
        "gb" => array("en" => "Great Britain", "de" => "Großbritannien"),
        "gd" => array("en" => "Grenada", "de" => "Grenada"),
        "ge" => array("en" => "Georgia", "de" => "Georgien"),
        "gf" => array("en" => "French Guyana", "de" => "Französisch Guyana"),
        "gh" => array("en" => "Ghana", "de" => "Ghana"),
        "gi" => array("en" => "Gibraltar", "de" => "Gibraltar"),
        "gl" => array("en" => "Greenland", "de" => "Grönland"),
        "gm" => array("en" => "Gambia", "de" => "Gambia"),
        "gn" => array("en" => "Guinea", "de" => "Guinea"),
        "gp" => array("en" => "Guadeloupe", "de" => "Guadeloupe"),
        "gq" => array("en" => "Equatorial Guinea", "de" => "Äquatorial Guinea"),
        "gr" => array("en" => "Greece", "de" => "Griechenland"),
        "gs" => array("en" => "S. Georgia & S. Sandwich Isls.", "de" => "South Georgia, South Sandwich Isl."),
        "gt" => array("en" => "Guatemala", "de" => "Guatemala"),
        "gu" => array("en" => "Guam (USA)", "de" => "Guam"),
        "gw" => array("en" => "Guinea Bissau", "de" => "Guinea Bissau"),
        "gy" => array("en" => "Guyana", "de" => "Guyana"),
        "hk" => array("en" => "Hong Kong", "de" => "Hong Kong"),
        "hm" => array("en" => "Heard and McDonald Islands", "de" => "Heard und McDonald Islands"),
        "hn" => array("en" => "Honduras", "de" => "Honduras"),
        "hr" => array("en" => "Croatia", "de" => "Kroatien"),
        "ht" => array("en" => "Haiti", "de" => "Haiti"),
        "hu" => array("en" => "Hungary", "de" => "Ungarn"),
        "id" => array("en" => "Indonesia", "de" => "Indonesien"),
        "ie" => array("en" => "Ireland", "de" => "Irland"),
        "il" => array("en" => "Israel", "de" => "Israel"),
        "in" => array("en" => "India", "de" => "Indien"),
        "io" => array("en" => "International", "de" => "Britisch-Indischer Ozean"),
        "iq" => array("en" => "Iraq", "de" => "Irak"),
        "ir" => array("en" => "Iran", "de" => "Iran"),
        "is" => array("en" => "Iceland", "de" => "Island"),
        "it" => array("en" => "Italy", "de" => "Italien"),
        "jm" => array("en" => "Jamaica", "de" => "Jamaika"),
        "jo" => array("en" => "Jordan", "de" => "Jordanien"),
        "jp" => array("en" => "Japan", "de" => "Japan"),
        "ke" => array("en" => "Kenya", "de" => "Kenia"),
        "kg" => array("en" => "Kyrgyzstan", "de" => "Kirgisistan"),
        "kh" => array("en" => "Cambodia", "de" => "Kambodscha"),
        "ki" => array("en" => "Kiribati", "de" => "Kiribati"),
        "km" => array("en" => "Comoros", "de" => "Komoren"),
        "kn" => array("en" => "Saint Kitts & Nevis Anguilla", "de" => "St. Kitts Nevis Anguilla"),
        "kp" => array("en" => "North Korea", "de" => "Nord Korea"),
        "kr" => array("en" => "South Korea", "de" => "Süd Korea"),
        "kw" => array("en" => "Kuwait", "de" => "Kuwait"),
        "ky" => array("en" => "Cayman Islands", "de" => "Kaiman Inseln"),
        "kz" => array("en" => "Kazakhstan", "de" => "Kasachstan"),
        "la" => array("en" => "Laos", "de" => "Laos"),
        "lb" => array("en" => "Lebanon", "de" => "Libanon"),
        "lc" => array("en" => "Saint Lucia", "de" => "Saint Lucia"),
        "li" => array("en" => "Liechtenstein", "de" => "Liechtenstein"),
        "lk" => array("en" => "Sri Lanka", "de" => "Sri Lanka"),
        "lr" => array("en" => "Liberia", "de" => "Liberia"),
        "ls" => array("en" => "Lesotho", "de" => "Lesotho"),
        "lt" => array("en" => "Lithuania", "de" => "Litauen"),
        "lu" => array("en" => "Luxembourg", "de" => "Luxemburg"),
        "lv" => array("en" => "Latvia", "de" => "Lettland"),
        "ly" => array("en" => "Libya", "de" => "Libyen"),
        "ma" => array("en" => "Morocco", "de" => "Marokko"),
        "mc" => array("en" => "Monaco", "de" => "Monaco"),
        "md" => array("en" => "Moldavia", "de" => "Moldavien"),
        "mg" => array("en" => "Madagascar", "de" => "Madagaskar"),
        "mh" => array("en" => "Marshall Islands", "de" => "Marshall Inseln"),
        "mk" => array("en" => "Macedonia", "de" => "Mazedonien"),
        "ml" => array("en" => "Mali", "de" => "Mali"),
        "mm" => array("en" => "Myanmar", "de" => "Birma"),
        "mn" => array("en" => "Mongolia", "de" => "Mongolei"),
        "mo" => array("en" => "Macau", "de" => "Macao"),
        "mp" => array("en" => "Northern Mariana Islands", "de" => "Marianen"),
        "mq" => array("en" => "Martinique", "de" => "Martinique"),
        "mr" => array("en" => "Mauritania", "de" => "Mauretanien"),
        "ms" => array("en" => "Montserrat", "de" => "Montserrat"),
        "mt" => array("en" => "Malta", "de" => "Malta"),
        "mu" => array("en" => "Mauritius", "de" => "Mauritius"),
        "mv" => array("en" => "Maldives", "de" => "Malediven"),
        "mw" => array("en" => "Malawi", "de" => "Malawi"),
        "mx" => array("en" => "Mexico", "de" => "Mexiko"),
        "my" => array("en" => "Malaysia", "de" => "Malaysia"),
        "mz" => array("en" => "Mozambique", "de" => "Mocambique"),
        "na" => array("en" => "Namibia", "de" => "Namibia"),
        "nc" => array("en" => "New Caledonia", "de" => "Neukaledonien"),
        "ne" => array("en" => "Niger", "de" => "Niger"),
        "nf" => array("en" => "Norfolk Island", "de" => "Norfolk Inseln"),
        "ng" => array("en" => "Nigeria", "de" => "Nigeria"),
        "ni" => array("en" => "Nicaragua", "de" => "Nicaragua"),
        "nl" => array("en" => "Netherlands", "de" => "Niederlande"),
        "no" => array("en" => "Norway", "de" => "Norwegen"),
        "np" => array("en" => "Nepal", "de" => "Nepal"),
        "nr" => array("en" => "Nauru", "de" => "Nauru"),
        "nu" => array("en" => "Niue", "de" => "Niue"),
        "nz" => array("en" => "New Zealand", "de" => "Neuseeland"),
        "om" => array("en" => "Oman", "de" => "Oman"),
        "pa" => array("en" => "Panama", "de" => "Panama"),
        "pe" => array("en" => "Peru", "de" => "Peru"),
        "pf" => array("en" => "Polynesia", "de" => "Französisch Polynesien"),
        "pg" => array("en" => "Papua New Guinea", "de" => "Papua Neuguinea"),
        "ph" => array("en" => "Philippines", "de" => "Philippinen"),
        "pk" => array("en" => "Pakistan", "de" => "Pakistan"),
        "pl" => array("en" => "Poland", "de" => "Polen"),
        "pm" => array("en" => "Saint Pierre and Miquelon", "de" => "St. Pierre und Miquelon"),
        "pn" => array("en" => "Pitcairn Island", "de" => "Pitcairn"),
        "pr" => array("en" => "Puerto Rico", "de" => "Puerto Rico"),
        "ps" => array("en" => "Palestine", "de" => "Palästina"),
        "pt" => array("en" => "Portugal", "de" => "Portugal"),
        "pw" => array("en" => "Palau", "de" => "Palau"),
        "py" => array("en" => "Paraguay", "de" => "Paraguay"),
        "qa" => array("en" => "Qatar", "de" => "Qatar"),
        "re" => array("en" => "Reunion", "de" => "Reunion"),
        "ro" => array("en" => "Romania", "de" => "Rumänien"),
        "rs" => array("en" => "Serbia", "de" => "Serbien"),
        "ru" => array("en" => "Russian Federation", "de" => "Russland"),
        "rw" => array("en" => "Rwanda", "de" => "Ruanda"),
        "sa" => array("en" => "Saudi Arabia", "de" => "Saudi Arabien"),
        "sb" => array("en" => "Solomon Islands", "de" => "Solomon Inseln"),
        "sc" => array("en" => "Seychelles", "de" => "Seychellen"),
        "sd" => array("en" => "Sudan", "de" => "Sudan"),
        "se" => array("en" => "Sweden", "de" => "Schweden"),
        "sg" => array("en" => "Singapore", "de" => "Singapur"),
        "sh" => array("en" => "Saint Helena", "de" => "St. Helena"),
        "si" => array("en" => "Slovenia", "de" => "Slowenien"),
        "sj" => array("en" => "Svalbard and Jan Mayen Islands", "de" => "Svalbard und Jan Mayen Islands"),
        "sk" => array("en" => "Slovak Republic", "de" => "Slowakei"),
        "sl" => array("en" => "Sierra Leone", "de" => "Sierra Leone"),
        "sm" => array("en" => "San Marino", "de" => "San Marino"),
        "sn" => array("en" => "Senegal", "de" => "Senegal"),
        "so" => array("en" => "Somalia", "de" => "Somalia"),
        "sr" => array("en" => "Suriname", "de" => "Surinam"),
        "ss" => array("en" => "South Sudan", "de" => "Süd-Sudan"),
        "st" => array("en" => "Saint Tome and Principe", "de" => "Sao Tome"),
        "sv" => array("en" => "El Salvador", "de" => "El Salvador"),
        "sy" => array("en" => "Syria", "de" => "Syrien"),
        "sz" => array("en" => "Swaziland", "de" => "Swasiland"),
        "tc" => array("en" => "Turks and Caicos Islands", "de" => "Turks und Kaikos Inseln"),
        "td" => array("en" => "Chad", "de" => "Tschad"),
        "tf" => array("en" => "French Southern Territories", "de" => "Französisches Süd-Territorium"),
        "tg" => array("en" => "Togo", "de" => "Togo"),
        "th" => array("en" => "Thailand", "de" => "Thailand"),
        "tj" => array("en" => "Tadjikistan", "de" => "Tadschikistan"),
        "tk" => array("en" => "Tokelau", "de" => "Tokelau"),
        "tm" => array("en" => "Turkmenistan", "de" => "Turkmenistan"),
        "tn" => array("en" => "Tunisia", "de" => "Tunesien"),
        "to" => array("en" => "Tonga", "de" => "Tonga"),
        "tp" => array("en" => "East Timor", "de" => "Timor"),
        "tr" => array("en" => "Turkey", "de" => "Türkei"),
        "tt" => array("en" => "Trinidad and Tobago", "de" => "Trinidad Tobago"),
        "tv" => array("en" => "Tuvalu", "de" => "Tuvalu"),
        "tw" => array("en" => "Taiwan", "de" => "Taiwan"),
        "tz" => array("en" => "Tanzania", "de" => "Tansania"),
        "ua" => array("en" => "Ukraine", "de" => "Ukraine"),
        "ug" => array("en" => "Uganda", "de" => "Uganda"),
        "uk" => array("en" => "United Kingdom", "de" => "Großbritannien"),
        "us" => array("en" => "United States", "de" => "Vereinigte Staaten von Amerika"),
        "uy" => array("en" => "Uruguay", "de" => "Uruguay"),
        "uz" => array("en" => "Uzbekistan", "de" => "Usbekistan"),
        "va" => array("en" => "Vatican City State", "de" => "Vatikan"),
        "vc" => array("en" => "Saint Vincent & Grenadines", "de" => "St. Vincent"),
        "ve" => array("en" => "Venezuela", "de" => "Venezuela"),
        "vg" => array("en" => "Virgin Islands (British)", "de" => "Virgin Island (Brit.)"),
        "vi" => array("en" => "Virgin Islands (USA)", "de" => "Virgin Island (USA)"),
        "vn" => array("en" => "Vietnam", "de" => "Vietnam"),
        "vu" => array("en" => "Vanuatu", "de" => "Vanuatu"),
        "wf" => array("en" => "Wallis and Futuna Islands", "de" => "Wallis et Futuna"),
        "ws" => array("en" => "Samoa", "de" => "Samoa"),
        "ye" => array("en" => "Yemen", "de" => "Jemen"),
        "yt" => array("en" => "Mayotte", "de" => "Mayotte"),
        "yu" => array("en" => "Yugoslavia", "de" => "Jugoslawien"),
        "za" => array("en" => "South Africa", "de" => "Südafrika"),
        "zm" => array("en" => "Zambia", "de" => "Sambia"),
        "zw" => array("en" => "Zimbabwe", "de" => "Zimbabwe")
    );
};
